//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3796e50f-7797-4408-b433-0fd4a4fe4890"",
            ""actions"": [
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""7524a51c-5750-4652-aba1-1b1fa3041f4f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""f9bfb5a2-2e63-4bed-97f1-1d9cc4190a60"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DropItem"",
                    ""type"": ""Button"",
                    ""id"": ""296981a9-53e4-4b38-9f79-66886d3738d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""aea0c3d0-6e2e-4005-8e68-b1c9402820c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""3f9c2a67-2771-4ee5-8270-e1937a87d6a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""9372f303-6fdc-48f8-a978-3dade3b13881"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseWheel"",
                    ""type"": ""Value"",
                    ""id"": ""8d9abc29-99de-4297-8077-c5f96bfc76c8"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Toolbelt Slot 1"",
                    ""type"": ""Button"",
                    ""id"": ""1d2360ad-5d8d-4b92-856b-3f41844394aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 2"",
                    ""type"": ""Button"",
                    ""id"": ""05b8ad5a-5c83-448f-b75a-8e7a0d051bbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 3"",
                    ""type"": ""Button"",
                    ""id"": ""61bb0fc0-a8ad-4577-8a9e-b1cca72368ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 4"",
                    ""type"": ""Button"",
                    ""id"": ""a9b2fe69-f2dd-4bb3-8bff-525096ecab52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 5"",
                    ""type"": ""Button"",
                    ""id"": ""1e5e6abc-47c0-46d8-8b0c-809d24a859e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 6"",
                    ""type"": ""Button"",
                    ""id"": ""cc4ffc7e-6042-4251-9047-579f1766182f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 7"",
                    ""type"": ""Button"",
                    ""id"": ""4abf3cbc-509f-4975-b860-7775b230b0f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 8"",
                    ""type"": ""Button"",
                    ""id"": ""24a901ab-2897-4a87-9c69-8e5f5aa25ef7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 9"",
                    ""type"": ""Button"",
                    ""id"": ""d12671df-a599-4f3e-92c8-48dbbae20814"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toolbelt Slot 10"",
                    ""type"": ""Button"",
                    ""id"": ""4f7edc89-eddb-4782-b076-58462e2393ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""ae000096-665b-4d8e-af50-af20a87a1324"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""3602a21e-6303-4d6c-bd63-940c54cc6e41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""df85b332-0cb5-433e-8413-cd3bac10d6c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControl"",
                    ""type"": ""Button"",
                    ""id"": ""d93ef8b4-c964-426a-90ec-bb43fd2db688"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugConsole"",
                    ""type"": ""Button"",
                    ""id"": ""fa7bc24b-df2f-4787-9f84-f5df46b615f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""ced07576-a1b8-49ad-9f4b-3186190014a3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCWObj"",
                    ""type"": ""Button"",
                    ""id"": ""c6567911-6b89-4bc3-9661-d3c7ac479c46"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VMirrorObj"",
                    ""type"": ""Button"",
                    ""id"": ""8ef533cf-64cb-4521-971c-cbc914e019d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HMirrorObj"",
                    ""type"": ""Button"",
                    ""id"": ""8e2bcfcc-7397-4c30-b888-c7b5f56252be"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e77ac590-d9ba-4737-9939-78721dd2d9d7"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""18eba1b0-6a46-412e-9545-91fa7873cb8c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84d30d90-4823-4f30-acf3-901c6fb19ba8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""38175828-b038-4084-b0e1-eb91d956b689"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""daed7649-61ce-4664-8517-5d4dd1fe26af"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""72999386-5cb2-4273-ac9a-c6e4ab27608d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""98861e4e-a008-4a21-ac43-41d7551618b7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a62afa33-9539-4545-b7b2-0cf42a2d96af"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f66d4560-4c97-433f-86a3-60cd8de291da"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b9994dda-4433-409a-af09-d7885265ebec"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""afad6be3-4ef1-4af5-a093-cc4e0d335c31"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""64abf5e8-1246-42f6-a766-ed081501c5b8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3adb89e1-63ea-4c11-8b00-9f98bcf033f3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16faa184-3578-4e41-a8e7-05aac5e6204a"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b01e0f4-00bb-4f6c-be98-55d4e1ba6189"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64db8075-5124-4a6b-826c-ae1f4aa05244"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac892a19-df69-4e95-972f-e1aaf0e562a3"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02317f8a-bd12-42ec-90b8-c82c2b56fb01"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MouseWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f85c9a9-8619-4712-810b-04112b0782af"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eed1062a-dcd4-4fc6-ae50-ac1235e405dc"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dbca511-aee8-4992-a5f7-06ed504d92f3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e25544e-89e6-44de-8cdb-7a01ce738f2e"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e832bcde-7afd-4613-92e7-4d9a956bc73d"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bfd29f4-5844-4cf7-9b6c-0861f309afaa"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b57b7996-fa1c-4ca3-badc-593c2fd63c45"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""662d96e9-e919-48fe-a90a-07b3e84b2624"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1acf5178-e493-4d87-8c1b-162d28b3a4c8"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b815c0f3-92fe-4a8f-ac04-41f6231560d6"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6841dc10-c86a-440b-b4d8-7bfe6128af14"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""020e74d3-d0a8-4810-8969-4ae63687e3ed"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e062052b-0a48-43c0-8ab5-1907f67b1c27"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58445825-be21-46b9-aa18-97d6369d1955"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""708604b1-b84b-4c76-840a-7dedc3951296"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29e6311b-a88a-45cb-84b4-6c71dbf732e9"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33a312fa-708c-4ce9-94fc-72cb907945fd"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cc98369-ec2c-49e9-be2d-1fe3a98aa846"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Toolbelt Slot 8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0eb64b5-16d1-41ff-ac2a-5274a0f4faaf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47da1f86-f307-4773-9e9b-793436bc5335"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f59d306-361d-492f-b32e-fcedb23e3a3b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""130ea143-6e6f-49d3-bc27-4e27e3925ffb"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c921e44-032d-44db-a529-aecc75b26d08"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""DebugConsole"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eee89619-b7e7-48a3-b3f2-c62f63918bf5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6fbbfe2-d3ff-4845-ad69-e7d9f10a53a2"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCWObj"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b1ec368-4b96-451d-a16a-0e8b3dfcf427"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VMirrorObj"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6463b988-456e-485b-a7ef-e9706df71b67"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMirrorObj"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DebugConsole"",
            ""id"": ""3d5c2138-c042-4ac6-8499-a2d8daa8ff2e"",
            ""actions"": [
                {
                    ""name"": ""CheatConsole"",
                    ""type"": ""Button"",
                    ""id"": ""98a53db1-5eff-4c6d-b635-328af30bdfbb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""f28a399c-567f-4906-8f97-a3c6e75d2a9a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowUp"",
                    ""type"": ""Button"",
                    ""id"": ""dcce0a54-542b-447e-9956-b85711eca21f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""81df1828-c897-414d-8906-f62d72132215"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugConsole"",
                    ""type"": ""Button"",
                    ""id"": ""68cd84e7-6300-428a-8b16-d35fe3ffd76b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""afc21a31-93f0-48fe-b864-76926f6c331a"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""CheatConsole"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaef7a3c-fe24-4826-be4b-d2feff50ecc3"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8843d09-01a2-4c84-ad63-07326290dfa0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b1bb6e8-453d-4b55-952b-fd8e1606e448"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b806d2b-0266-4d4f-81d0-954fef3ed10c"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f11999f-1ad4-47ee-a41b-7eed675a897f"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""DebugConsole"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dialogue"",
            ""id"": ""6c875ff1-6526-4eb7-b540-c7dd2edf443a"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""c8ad8dad-9ba7-435b-96ae-5f1c590df52a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResponseDown"",
                    ""type"": ""Button"",
                    ""id"": ""f8b85071-8aeb-4159-bd1e-f1e5aa7dc944"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResponseUp"",
                    ""type"": ""Button"",
                    ""id"": ""77036935-57fc-4e4f-a7c9-1ff63c7d59b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""476782c4-a3d2-4974-bc59-2afd84932bdc"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c91d286c-4028-440f-abfa-53ef43369aca"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06e51dd0-5635-4f57-8c78-59eb596ad4d3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e889f308-859d-464b-b0ba-057f1d183aad"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfa02b8f-5f8f-463a-90b0-c69170242154"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResponseDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c4c9163-7907-490b-9eae-042f1408a1e8"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResponseDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c71f0477-814a-423e-8e85-f81e2a23f545"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResponseUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""717a7405-46d3-448a-99c4-c2fc458624dd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResponseUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": []
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_DropItem = m_Player.FindAction("DropItem", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_Inventory = m_Player.FindAction("Inventory", throwIfNotFound: true);
        m_Player_Escape = m_Player.FindAction("Escape", throwIfNotFound: true);
        m_Player_MouseWheel = m_Player.FindAction("MouseWheel", throwIfNotFound: true);
        m_Player_ToolbeltSlot1 = m_Player.FindAction("Toolbelt Slot 1", throwIfNotFound: true);
        m_Player_ToolbeltSlot2 = m_Player.FindAction("Toolbelt Slot 2", throwIfNotFound: true);
        m_Player_ToolbeltSlot3 = m_Player.FindAction("Toolbelt Slot 3", throwIfNotFound: true);
        m_Player_ToolbeltSlot4 = m_Player.FindAction("Toolbelt Slot 4", throwIfNotFound: true);
        m_Player_ToolbeltSlot5 = m_Player.FindAction("Toolbelt Slot 5", throwIfNotFound: true);
        m_Player_ToolbeltSlot6 = m_Player.FindAction("Toolbelt Slot 6", throwIfNotFound: true);
        m_Player_ToolbeltSlot7 = m_Player.FindAction("Toolbelt Slot 7", throwIfNotFound: true);
        m_Player_ToolbeltSlot8 = m_Player.FindAction("Toolbelt Slot 8", throwIfNotFound: true);
        m_Player_ToolbeltSlot9 = m_Player.FindAction("Toolbelt Slot 9", throwIfNotFound: true);
        m_Player_ToolbeltSlot10 = m_Player.FindAction("Toolbelt Slot 10", throwIfNotFound: true);
        m_Player_LeftClick = m_Player.FindAction("LeftClick", throwIfNotFound: true);
        m_Player_RightClick = m_Player.FindAction("RightClick", throwIfNotFound: true);
        m_Player_PointerPosition = m_Player.FindAction("PointerPosition", throwIfNotFound: true);
        m_Player_LeftControl = m_Player.FindAction("LeftControl", throwIfNotFound: true);
        m_Player_DebugConsole = m_Player.FindAction("DebugConsole", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_RotateCWObj = m_Player.FindAction("RotateCWObj", throwIfNotFound: true);
        m_Player_VMirrorObj = m_Player.FindAction("VMirrorObj", throwIfNotFound: true);
        m_Player_HMirrorObj = m_Player.FindAction("HMirrorObj", throwIfNotFound: true);
        // DebugConsole
        m_DebugConsole = asset.FindActionMap("DebugConsole", throwIfNotFound: true);
        m_DebugConsole_CheatConsole = m_DebugConsole.FindAction("CheatConsole", throwIfNotFound: true);
        m_DebugConsole_Enter = m_DebugConsole.FindAction("Enter", throwIfNotFound: true);
        m_DebugConsole_ArrowUp = m_DebugConsole.FindAction("ArrowUp", throwIfNotFound: true);
        m_DebugConsole_ArrowDown = m_DebugConsole.FindAction("ArrowDown", throwIfNotFound: true);
        m_DebugConsole_DebugConsole = m_DebugConsole.FindAction("DebugConsole", throwIfNotFound: true);
        // Dialogue
        m_Dialogue = asset.FindActionMap("Dialogue", throwIfNotFound: true);
        m_Dialogue_Continue = m_Dialogue.FindAction("Continue", throwIfNotFound: true);
        m_Dialogue_ResponseDown = m_Dialogue.FindAction("ResponseDown", throwIfNotFound: true);
        m_Dialogue_ResponseUp = m_Dialogue.FindAction("ResponseUp", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputActions.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_DebugConsole.enabled, "This will cause a leak and performance issues, PlayerInputActions.DebugConsole.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Dialogue.enabled, "This will cause a leak and performance issues, PlayerInputActions.Dialogue.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_DropItem;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_Inventory;
    private readonly InputAction m_Player_Escape;
    private readonly InputAction m_Player_MouseWheel;
    private readonly InputAction m_Player_ToolbeltSlot1;
    private readonly InputAction m_Player_ToolbeltSlot2;
    private readonly InputAction m_Player_ToolbeltSlot3;
    private readonly InputAction m_Player_ToolbeltSlot4;
    private readonly InputAction m_Player_ToolbeltSlot5;
    private readonly InputAction m_Player_ToolbeltSlot6;
    private readonly InputAction m_Player_ToolbeltSlot7;
    private readonly InputAction m_Player_ToolbeltSlot8;
    private readonly InputAction m_Player_ToolbeltSlot9;
    private readonly InputAction m_Player_ToolbeltSlot10;
    private readonly InputAction m_Player_LeftClick;
    private readonly InputAction m_Player_RightClick;
    private readonly InputAction m_Player_PointerPosition;
    private readonly InputAction m_Player_LeftControl;
    private readonly InputAction m_Player_DebugConsole;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_RotateCWObj;
    private readonly InputAction m_Player_VMirrorObj;
    private readonly InputAction m_Player_HMirrorObj;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @DropItem => m_Wrapper.m_Player_DropItem;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @Inventory => m_Wrapper.m_Player_Inventory;
        public InputAction @Escape => m_Wrapper.m_Player_Escape;
        public InputAction @MouseWheel => m_Wrapper.m_Player_MouseWheel;
        public InputAction @ToolbeltSlot1 => m_Wrapper.m_Player_ToolbeltSlot1;
        public InputAction @ToolbeltSlot2 => m_Wrapper.m_Player_ToolbeltSlot2;
        public InputAction @ToolbeltSlot3 => m_Wrapper.m_Player_ToolbeltSlot3;
        public InputAction @ToolbeltSlot4 => m_Wrapper.m_Player_ToolbeltSlot4;
        public InputAction @ToolbeltSlot5 => m_Wrapper.m_Player_ToolbeltSlot5;
        public InputAction @ToolbeltSlot6 => m_Wrapper.m_Player_ToolbeltSlot6;
        public InputAction @ToolbeltSlot7 => m_Wrapper.m_Player_ToolbeltSlot7;
        public InputAction @ToolbeltSlot8 => m_Wrapper.m_Player_ToolbeltSlot8;
        public InputAction @ToolbeltSlot9 => m_Wrapper.m_Player_ToolbeltSlot9;
        public InputAction @ToolbeltSlot10 => m_Wrapper.m_Player_ToolbeltSlot10;
        public InputAction @LeftClick => m_Wrapper.m_Player_LeftClick;
        public InputAction @RightClick => m_Wrapper.m_Player_RightClick;
        public InputAction @PointerPosition => m_Wrapper.m_Player_PointerPosition;
        public InputAction @LeftControl => m_Wrapper.m_Player_LeftControl;
        public InputAction @DebugConsole => m_Wrapper.m_Player_DebugConsole;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @RotateCWObj => m_Wrapper.m_Player_RotateCWObj;
        public InputAction @VMirrorObj => m_Wrapper.m_Player_VMirrorObj;
        public InputAction @HMirrorObj => m_Wrapper.m_Player_HMirrorObj;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @DropItem.started += instance.OnDropItem;
            @DropItem.performed += instance.OnDropItem;
            @DropItem.canceled += instance.OnDropItem;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
            @MouseWheel.started += instance.OnMouseWheel;
            @MouseWheel.performed += instance.OnMouseWheel;
            @MouseWheel.canceled += instance.OnMouseWheel;
            @ToolbeltSlot1.started += instance.OnToolbeltSlot1;
            @ToolbeltSlot1.performed += instance.OnToolbeltSlot1;
            @ToolbeltSlot1.canceled += instance.OnToolbeltSlot1;
            @ToolbeltSlot2.started += instance.OnToolbeltSlot2;
            @ToolbeltSlot2.performed += instance.OnToolbeltSlot2;
            @ToolbeltSlot2.canceled += instance.OnToolbeltSlot2;
            @ToolbeltSlot3.started += instance.OnToolbeltSlot3;
            @ToolbeltSlot3.performed += instance.OnToolbeltSlot3;
            @ToolbeltSlot3.canceled += instance.OnToolbeltSlot3;
            @ToolbeltSlot4.started += instance.OnToolbeltSlot4;
            @ToolbeltSlot4.performed += instance.OnToolbeltSlot4;
            @ToolbeltSlot4.canceled += instance.OnToolbeltSlot4;
            @ToolbeltSlot5.started += instance.OnToolbeltSlot5;
            @ToolbeltSlot5.performed += instance.OnToolbeltSlot5;
            @ToolbeltSlot5.canceled += instance.OnToolbeltSlot5;
            @ToolbeltSlot6.started += instance.OnToolbeltSlot6;
            @ToolbeltSlot6.performed += instance.OnToolbeltSlot6;
            @ToolbeltSlot6.canceled += instance.OnToolbeltSlot6;
            @ToolbeltSlot7.started += instance.OnToolbeltSlot7;
            @ToolbeltSlot7.performed += instance.OnToolbeltSlot7;
            @ToolbeltSlot7.canceled += instance.OnToolbeltSlot7;
            @ToolbeltSlot8.started += instance.OnToolbeltSlot8;
            @ToolbeltSlot8.performed += instance.OnToolbeltSlot8;
            @ToolbeltSlot8.canceled += instance.OnToolbeltSlot8;
            @ToolbeltSlot9.started += instance.OnToolbeltSlot9;
            @ToolbeltSlot9.performed += instance.OnToolbeltSlot9;
            @ToolbeltSlot9.canceled += instance.OnToolbeltSlot9;
            @ToolbeltSlot10.started += instance.OnToolbeltSlot10;
            @ToolbeltSlot10.performed += instance.OnToolbeltSlot10;
            @ToolbeltSlot10.canceled += instance.OnToolbeltSlot10;
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @PointerPosition.started += instance.OnPointerPosition;
            @PointerPosition.performed += instance.OnPointerPosition;
            @PointerPosition.canceled += instance.OnPointerPosition;
            @LeftControl.started += instance.OnLeftControl;
            @LeftControl.performed += instance.OnLeftControl;
            @LeftControl.canceled += instance.OnLeftControl;
            @DebugConsole.started += instance.OnDebugConsole;
            @DebugConsole.performed += instance.OnDebugConsole;
            @DebugConsole.canceled += instance.OnDebugConsole;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @RotateCWObj.started += instance.OnRotateCWObj;
            @RotateCWObj.performed += instance.OnRotateCWObj;
            @RotateCWObj.canceled += instance.OnRotateCWObj;
            @VMirrorObj.started += instance.OnVMirrorObj;
            @VMirrorObj.performed += instance.OnVMirrorObj;
            @VMirrorObj.canceled += instance.OnVMirrorObj;
            @HMirrorObj.started += instance.OnHMirrorObj;
            @HMirrorObj.performed += instance.OnHMirrorObj;
            @HMirrorObj.canceled += instance.OnHMirrorObj;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @DropItem.started -= instance.OnDropItem;
            @DropItem.performed -= instance.OnDropItem;
            @DropItem.canceled -= instance.OnDropItem;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
            @MouseWheel.started -= instance.OnMouseWheel;
            @MouseWheel.performed -= instance.OnMouseWheel;
            @MouseWheel.canceled -= instance.OnMouseWheel;
            @ToolbeltSlot1.started -= instance.OnToolbeltSlot1;
            @ToolbeltSlot1.performed -= instance.OnToolbeltSlot1;
            @ToolbeltSlot1.canceled -= instance.OnToolbeltSlot1;
            @ToolbeltSlot2.started -= instance.OnToolbeltSlot2;
            @ToolbeltSlot2.performed -= instance.OnToolbeltSlot2;
            @ToolbeltSlot2.canceled -= instance.OnToolbeltSlot2;
            @ToolbeltSlot3.started -= instance.OnToolbeltSlot3;
            @ToolbeltSlot3.performed -= instance.OnToolbeltSlot3;
            @ToolbeltSlot3.canceled -= instance.OnToolbeltSlot3;
            @ToolbeltSlot4.started -= instance.OnToolbeltSlot4;
            @ToolbeltSlot4.performed -= instance.OnToolbeltSlot4;
            @ToolbeltSlot4.canceled -= instance.OnToolbeltSlot4;
            @ToolbeltSlot5.started -= instance.OnToolbeltSlot5;
            @ToolbeltSlot5.performed -= instance.OnToolbeltSlot5;
            @ToolbeltSlot5.canceled -= instance.OnToolbeltSlot5;
            @ToolbeltSlot6.started -= instance.OnToolbeltSlot6;
            @ToolbeltSlot6.performed -= instance.OnToolbeltSlot6;
            @ToolbeltSlot6.canceled -= instance.OnToolbeltSlot6;
            @ToolbeltSlot7.started -= instance.OnToolbeltSlot7;
            @ToolbeltSlot7.performed -= instance.OnToolbeltSlot7;
            @ToolbeltSlot7.canceled -= instance.OnToolbeltSlot7;
            @ToolbeltSlot8.started -= instance.OnToolbeltSlot8;
            @ToolbeltSlot8.performed -= instance.OnToolbeltSlot8;
            @ToolbeltSlot8.canceled -= instance.OnToolbeltSlot8;
            @ToolbeltSlot9.started -= instance.OnToolbeltSlot9;
            @ToolbeltSlot9.performed -= instance.OnToolbeltSlot9;
            @ToolbeltSlot9.canceled -= instance.OnToolbeltSlot9;
            @ToolbeltSlot10.started -= instance.OnToolbeltSlot10;
            @ToolbeltSlot10.performed -= instance.OnToolbeltSlot10;
            @ToolbeltSlot10.canceled -= instance.OnToolbeltSlot10;
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @PointerPosition.started -= instance.OnPointerPosition;
            @PointerPosition.performed -= instance.OnPointerPosition;
            @PointerPosition.canceled -= instance.OnPointerPosition;
            @LeftControl.started -= instance.OnLeftControl;
            @LeftControl.performed -= instance.OnLeftControl;
            @LeftControl.canceled -= instance.OnLeftControl;
            @DebugConsole.started -= instance.OnDebugConsole;
            @DebugConsole.performed -= instance.OnDebugConsole;
            @DebugConsole.canceled -= instance.OnDebugConsole;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @RotateCWObj.started -= instance.OnRotateCWObj;
            @RotateCWObj.performed -= instance.OnRotateCWObj;
            @RotateCWObj.canceled -= instance.OnRotateCWObj;
            @VMirrorObj.started -= instance.OnVMirrorObj;
            @VMirrorObj.performed -= instance.OnVMirrorObj;
            @VMirrorObj.canceled -= instance.OnVMirrorObj;
            @HMirrorObj.started -= instance.OnHMirrorObj;
            @HMirrorObj.performed -= instance.OnHMirrorObj;
            @HMirrorObj.canceled -= instance.OnHMirrorObj;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // DebugConsole
    private readonly InputActionMap m_DebugConsole;
    private List<IDebugConsoleActions> m_DebugConsoleActionsCallbackInterfaces = new List<IDebugConsoleActions>();
    private readonly InputAction m_DebugConsole_CheatConsole;
    private readonly InputAction m_DebugConsole_Enter;
    private readonly InputAction m_DebugConsole_ArrowUp;
    private readonly InputAction m_DebugConsole_ArrowDown;
    private readonly InputAction m_DebugConsole_DebugConsole;
    public struct DebugConsoleActions
    {
        private @PlayerInputActions m_Wrapper;
        public DebugConsoleActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @CheatConsole => m_Wrapper.m_DebugConsole_CheatConsole;
        public InputAction @Enter => m_Wrapper.m_DebugConsole_Enter;
        public InputAction @ArrowUp => m_Wrapper.m_DebugConsole_ArrowUp;
        public InputAction @ArrowDown => m_Wrapper.m_DebugConsole_ArrowDown;
        public InputAction @DebugConsole => m_Wrapper.m_DebugConsole_DebugConsole;
        public InputActionMap Get() { return m_Wrapper.m_DebugConsole; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugConsoleActions set) { return set.Get(); }
        public void AddCallbacks(IDebugConsoleActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugConsoleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugConsoleActionsCallbackInterfaces.Add(instance);
            @CheatConsole.started += instance.OnCheatConsole;
            @CheatConsole.performed += instance.OnCheatConsole;
            @CheatConsole.canceled += instance.OnCheatConsole;
            @Enter.started += instance.OnEnter;
            @Enter.performed += instance.OnEnter;
            @Enter.canceled += instance.OnEnter;
            @ArrowUp.started += instance.OnArrowUp;
            @ArrowUp.performed += instance.OnArrowUp;
            @ArrowUp.canceled += instance.OnArrowUp;
            @ArrowDown.started += instance.OnArrowDown;
            @ArrowDown.performed += instance.OnArrowDown;
            @ArrowDown.canceled += instance.OnArrowDown;
            @DebugConsole.started += instance.OnDebugConsole;
            @DebugConsole.performed += instance.OnDebugConsole;
            @DebugConsole.canceled += instance.OnDebugConsole;
        }

        private void UnregisterCallbacks(IDebugConsoleActions instance)
        {
            @CheatConsole.started -= instance.OnCheatConsole;
            @CheatConsole.performed -= instance.OnCheatConsole;
            @CheatConsole.canceled -= instance.OnCheatConsole;
            @Enter.started -= instance.OnEnter;
            @Enter.performed -= instance.OnEnter;
            @Enter.canceled -= instance.OnEnter;
            @ArrowUp.started -= instance.OnArrowUp;
            @ArrowUp.performed -= instance.OnArrowUp;
            @ArrowUp.canceled -= instance.OnArrowUp;
            @ArrowDown.started -= instance.OnArrowDown;
            @ArrowDown.performed -= instance.OnArrowDown;
            @ArrowDown.canceled -= instance.OnArrowDown;
            @DebugConsole.started -= instance.OnDebugConsole;
            @DebugConsole.performed -= instance.OnDebugConsole;
            @DebugConsole.canceled -= instance.OnDebugConsole;
        }

        public void RemoveCallbacks(IDebugConsoleActions instance)
        {
            if (m_Wrapper.m_DebugConsoleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDebugConsoleActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugConsoleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugConsoleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DebugConsoleActions @DebugConsole => new DebugConsoleActions(this);

    // Dialogue
    private readonly InputActionMap m_Dialogue;
    private List<IDialogueActions> m_DialogueActionsCallbackInterfaces = new List<IDialogueActions>();
    private readonly InputAction m_Dialogue_Continue;
    private readonly InputAction m_Dialogue_ResponseDown;
    private readonly InputAction m_Dialogue_ResponseUp;
    public struct DialogueActions
    {
        private @PlayerInputActions m_Wrapper;
        public DialogueActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Continue => m_Wrapper.m_Dialogue_Continue;
        public InputAction @ResponseDown => m_Wrapper.m_Dialogue_ResponseDown;
        public InputAction @ResponseUp => m_Wrapper.m_Dialogue_ResponseUp;
        public InputActionMap Get() { return m_Wrapper.m_Dialogue; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueActions set) { return set.Get(); }
        public void AddCallbacks(IDialogueActions instance)
        {
            if (instance == null || m_Wrapper.m_DialogueActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DialogueActionsCallbackInterfaces.Add(instance);
            @Continue.started += instance.OnContinue;
            @Continue.performed += instance.OnContinue;
            @Continue.canceled += instance.OnContinue;
            @ResponseDown.started += instance.OnResponseDown;
            @ResponseDown.performed += instance.OnResponseDown;
            @ResponseDown.canceled += instance.OnResponseDown;
            @ResponseUp.started += instance.OnResponseUp;
            @ResponseUp.performed += instance.OnResponseUp;
            @ResponseUp.canceled += instance.OnResponseUp;
        }

        private void UnregisterCallbacks(IDialogueActions instance)
        {
            @Continue.started -= instance.OnContinue;
            @Continue.performed -= instance.OnContinue;
            @Continue.canceled -= instance.OnContinue;
            @ResponseDown.started -= instance.OnResponseDown;
            @ResponseDown.performed -= instance.OnResponseDown;
            @ResponseDown.canceled -= instance.OnResponseDown;
            @ResponseUp.started -= instance.OnResponseUp;
            @ResponseUp.performed -= instance.OnResponseUp;
            @ResponseUp.canceled -= instance.OnResponseUp;
        }

        public void RemoveCallbacks(IDialogueActions instance)
        {
            if (m_Wrapper.m_DialogueActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDialogueActions instance)
        {
            foreach (var item in m_Wrapper.m_DialogueActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DialogueActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DialogueActions @Dialogue => new DialogueActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnRun(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnDropItem(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnMouseWheel(InputAction.CallbackContext context);
        void OnToolbeltSlot1(InputAction.CallbackContext context);
        void OnToolbeltSlot2(InputAction.CallbackContext context);
        void OnToolbeltSlot3(InputAction.CallbackContext context);
        void OnToolbeltSlot4(InputAction.CallbackContext context);
        void OnToolbeltSlot5(InputAction.CallbackContext context);
        void OnToolbeltSlot6(InputAction.CallbackContext context);
        void OnToolbeltSlot7(InputAction.CallbackContext context);
        void OnToolbeltSlot8(InputAction.CallbackContext context);
        void OnToolbeltSlot9(InputAction.CallbackContext context);
        void OnToolbeltSlot10(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnPointerPosition(InputAction.CallbackContext context);
        void OnLeftControl(InputAction.CallbackContext context);
        void OnDebugConsole(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnRotateCWObj(InputAction.CallbackContext context);
        void OnVMirrorObj(InputAction.CallbackContext context);
        void OnHMirrorObj(InputAction.CallbackContext context);
    }
    public interface IDebugConsoleActions
    {
        void OnCheatConsole(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnArrowUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnDebugConsole(InputAction.CallbackContext context);
    }
    public interface IDialogueActions
    {
        void OnContinue(InputAction.CallbackContext context);
        void OnResponseDown(InputAction.CallbackContext context);
        void OnResponseUp(InputAction.CallbackContext context);
    }
}
